### ISSUE TITLE
UNREFERENCED_OPEN_API_FILE being flagged for example files

### ISSUE THREAD

**Issue by nschonni** [Azure/avocado#11]
https://dev.azure.com/azure-sdk/public/_build/results?buildId=10830&view=logs&jobId=f10f5372-40ed-54fc-caa4-b1cb5bd1252b&taskId=d3b2b841-a93b-5fa5-47c3-d8c4f6eae6e3&lineStart=33&lineEnd=39&colStart=1&colEnd=1

It looks like changed example files are getting marked as unreferenced from the README. Since they aren't something normally referenced from the README, that should be supressed.

**Comment by sergey-shandar** [comment]
Yes, we need to change the message to "UNREFERENCED_JSON_FILE"

**Comment by nschonni** [comment]
Yeah, that would make sense for the example files, but I'm not sure if it's still a false-positive

**Comment by sergey-shandar** [comment]
The issue with `adhybridhealthservice` should be fixed https://github.com/Azure/avocado/issues/9. I will keep this issue open to track an error message change.

**Comment by sergey-shandar** [comment]
The message should be changed in PR #13
