### ISSUE TITLE
Updating paths should trigger reference check from all files in repo

### ISSUE THREAD

**Issue by veronicagg** [Azure/avocado#12]
Example  like https://github.com/Azure/azure-rest-api-specs-pr/pull/662/files#diff-515630a4d2183ab2f6ea6fc7fa571d87R409 where a ref to a common type "$ref": "../../../../../common-types/resource-management/v1/types.json#/parameters/ApiVersionParameter" could get broken due to an update in its path - it's really hard to catch if we don't have a tool to check on the consistency of the repo.
I would want our tool to flag broken references if for example "resource-management" changed to "resource-manager", and indicate all the files where the reference should be updated.

**Comment by sergey-shandar** [comment]
Possible duplication #15

**Comment by ruowan** [comment]
Solved in this PR #39
