### ISSUE TITLE
Avocado should analyze all references globally.

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/avocado#15]

**Comment by sergey-shandar** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/6313#pullrequestreview-249077364

**Comment by sergey-shandar** [comment]
1. We need to build a graph of all references and then report errors by analyzing this graph. (for Avocado CI)
2. `structuralDiff` function should use this graph to report effected specs/files. (for rest-api-specs-scripts CI).

**Comment by ruowan** [comment]
solved in #39
