### ISSUE TITLE
Avocado should recognize Swagger and example files

### ISSUE THREAD

**Issue by kpajdzik** [Azure/avocado#20]
Sample failure: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=17144
Sample PR: https://github.com/Azure/azure-rest-api-specs-pr/pull/730

**Comment by ruowan** [comment]
Is this issue is about Avocado should ignore `refs` in example files? @sergey-shandar

**Comment by sergey-shandar** [comment]
Duplicate #22

**Comment by ruowan** [comment]
#42 solved
