### ISSUE TITLE
Differentiate between ways files can be UNREFERENCED_JSON_FILE

### ISSUE THREAD

**Issue by nschonni** [Azure/avocado#22]
Looks like `UNREFERENCED_JSON_FILE` can be triggered for a few reasons
1. It is an Swagger file, and it isn't referenced by the README
1. It is an example file that isn't referenced by a Swagger file
1. It is an example file that is referenced by the Swagger file, but the Swagger file isn't referenced in the README

It seems like all these cases currently outputh the message "The JSON file is not referenced from the readme file.", but it might be good for a more specific error (if that is possible)

**Comment by ruowan** [comment]
I think item 1 contains item 3. I suggest two specific error messages.

**Comment by nschonni** [comment]
OK, I added tests for the 3 scenarios in #25, but i'm fine if you want to treat 2 of them together
