### ISSUE TITLE
Flag when swagger isn't under stable or preview parent folder

### ISSUE THREAD

**Issue by nschonni** [Azure/avocado#41]
See https://github.com/Azure/azure-rest-api-specs/issues/6624
When an API isn't put under a stable or preview folder, there is no current warning. I think Avocado is probably the right place to check that.

**Comment by ruowan** [comment]
It seems that this PR has been resolved.  Is it necessary to check whether API specs under a stable or preview folder? @sergey-shandar

**Comment by ruowan** [comment]
Closed, since current rule already covered.
